[project]
name = "cube-permutations"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.cube-permutations]
path = "contracts/cube-permutations.clar"
depends_on = ["sip-009-nft-trait"]

[contracts.dao]
path = "contracts/dao.clar"
depends_on = []

[contracts.market]
path = "contracts/market.clar"
depends_on = []

[contracts.sip-009-nft-trait]
path = "contracts/sip-009-nft-trait.clar"
depends_on = []

[repl]
costs_version = 1
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
